###############-VERSION-###################
version: '3.7'

################-SERVICIOS-################

services:


###################-SERVIDOR-#########################  
  grpc_server:
    container_name: servidor-grpc
    build: ./ServerJS
    depends_on:
      - postgres
    ports:
      - "8030:8030"

#################-POSTGRES-##########################
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./Database/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tarea1
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"
